// This file is generated by Midway-Swagger
var Midway = require('testarmada-midway');
Midway.id('Midway-swagger');

Midway.route({
  id: 'pets-GET',
  label: 'swagger-pets-GET',
  method: 'GET',
  path: '/pets',
  handler: function () {}
});

Midway.route({
  id: 'pets-POST',
  label: 'swagger-pets-POST',
  method: 'POST',
  path: '/pets',
  handler: function () {}
});

Midway.route({
  id: 'pets-id-GET',
  label: 'swagger-pets-id-GET',
  method: 'GET',
  path: '/pets/{id}',
  handler: function () {}
});

Midway.route({
  id: 'pets-id-DELETE',
  label: 'swagger-pets-id-DELETE',
  method: 'DELETE',
  path: '/pets/{id}',
  handler: function () {}
});

Midway.route({
  id: 'pets-id-items-GET',
  label: 'swagger-pets-id-items-GET',
  method: 'GET',
  path: '/pets/{id}/items',
  handler: function () {}
});

Midway.route({
  id: 'pets-id-items-POST',
  label: 'swagger-pets-id-items-POST',
  method: 'POST',
  path: '/pets/{id}/items',
  handler: function () {}
});
