/**
* MIT License
*
* Copyright (c) 2018-present, Walmart Inc.,
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*/
var RestHelper = require('./rest-helper');
var Logger = require('testarmada-midway-logger');
var Fs = require('fs');
var StringBuilder = require('stringbuilder');
var Path = require('path');
var Midway = require('testarmada-midway');

const info = {
  'version': '1.0.0',
  'title': 'Dummy info',
  'description': 'Dummy description for swagger-2.0 specification',
  'termsOfService': 'Dummy',
  'contact': {
    'name': 'Dummy contact'
  },
  'license': {
    'name': 'MIT'
  }
};

var defaultHandlerStatic = {
  handler: function (req, reply) {
    Midway.util.respondWithFile(this, reply);
  }
};

var addDummyInfoToDefinition = function (swaggerDef) {
  // Add info if missing from definition
  if (swaggerDef.info) {
    swaggerDef.info = info;
  }
};

module.exports = {
  addRoutesToMidway: function (midwayInstance, routes) {
    routes.forEach(function (route) {
      midwayInstance.route(route);
    });

    return midwayInstance;
  },

  getSwaggerFile: function (options, callback) {
    RestHelper(options, function (err, swaggerDefinition) {
      if (err) {
        return callback(err);
      }
      if (swaggerDefinition) {
        Logger.debug('Swagger file from remote service: '
          + JSON.stringify(swaggerDefinition, null, 2));
        addDummyInfoToDefinition(swaggerDefinition);
        return callback(null, swaggerDefinition);
      }
    });
  },

  getDefaultHandler: function (midway) {
    if (midway) {
      var handler = {
        handler: function (req, reply) {
          midway.util.respondWithFile(this, reply);
        }
      };

      return handler;
    } else {
      return defaultHandlerStatic;
    }
  },

  createMidwayProperties: function (routes, options) {
    routes.forEach(function (route, i) {
      route.id = route.name;
      route.label = route.name;
      route.method = route.method.toUpperCase();

      if (options.useDefaultHandler) {
        route.handler = options.useDefaultHandler.handler;
      }

      routes[i] = route;
    });
  },

  storeEndpointsToFile: function (routes, options, callback) {
    // setting up endpoints.js directory
    var dir = options.endpointsFilePath || process.cwd();
    if (!Fs.existsSync(dir)) {
      Fs.mkdirSync(dir);
    }

    //Build the file content
    var quote = '\'';
    var quoteWithComma = '\',';
    var fileContent = new StringBuilder({newline: '\r\n'});
    fileContent.appendLine('// This file is generated by Midway-Swagger');
    fileContent.appendLine('var Midway = require(\'testarmada-midway\');');
    fileContent.appendLine('Midway.id(\'Midway-swagger\');');
    routes.forEach(function (route) {
      fileContent.appendLine();
      fileContent.appendLine('Midway.route({');
      fileContent.appendLine('  id: ' + quote + ((route.path.replace(/\//, '')).replace(/\//g, '-')).replace(/{|}/g, '')
        + '-' + route.method + quoteWithComma);
      fileContent.appendLine('  label: ' + quote + 'swagger-' + ((route.path.replace(/\//, ''))
          .replace(/\//g, '-')).replace(/{|}/g, '') + '-' + route.method + quoteWithComma);
      fileContent.appendLine('  method: ' + quote + route.method + quoteWithComma);
      fileContent.appendLine('  path: ' + quote + route.path + quoteWithComma);
      fileContent.appendLine('  handler: ' + (route.handler.toString()));
      fileContent.appendLine('});');
    });

    fileContent.build(function (err, content) {
      if (err) {
        Logger.warn('Problem when building contents for endpoints-swagger.js file');
        return callback(err);
      }
      Fs.writeFile(Path.join(dir, 'endpoints-swagger.js'), content, function (err) {
        if (err) {
          return Logger.error('Problem creating endpoints-swagger.js ' + err);
        }
        return callback(null);
      });
    });
  }

};
